import { Inter, Lexend, Lexend_Deca } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })
const lexend = Lexend_Deca({ subsets: ['latin'] })
export const metadata = {
  title: 'mymini.corner',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>{children}
      </body>
    </html>
  )
}
